### ISSUE TITLE
Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1

### ISSUE THREAD

**Issue by navsaini53** [start-react/native-starter-kit#101]
all of my apps created using this repo suddenly broke out while running "react-native run-android".
![screenshot from 2017-05-27 16-41-18](https://cloud.githubusercontent.com/assets/7802443/26520985/5437b4e8-42fb-11e7-9950-e6837d812dbc.png)

**Comment by geekrishabh** [comment]
@navsaini53 please let us know the branch that you are using and the steps to reproduce the error.

**Comment by SupriyaKalghatgi** [comment]
@navsaini53 This is not because of Native Starter Kit
The error log says **could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1**
So you need to check the configurations for`react-native-image-crop-picker`
#[14223](https://github.com/facebook/react-native/issues/14223) might be helpful
