### ISSUE TITLE
working example of fetch in redux?

### ISSUE THREAD

**Issue by polygoal** [start-react/native-starter-kit#43]
I seems like your implementation of redux differs from what we've been using so far.

Do you have a working code example of async fetch in redux?

Would be also great for the documentation of this starterkit.

Thanks and best wishes,
Peer

**Comment by sanketsahu** [comment]
About the Async, we don't have an example with the Starter Kit at the moment but we have used [Redux Thunk](https://github.com/gaearon/redux-thunk) and [Redux Saga](https://github.com/yelouafi/redux-saga) with other projects.

Also, we recently launched [Native Starter Pro with Backend](https://strapmobile.com/native-starter-pro-back-end/) where we have back-end APIs implemented using Express / Node.js and the state management in React Native uses [MobX](https://mobxjs.github.io/mobx/) (instead of Redux). We are switching to [MobX](https://mobxjs.github.io/mobx/) big time.
